// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"github.com/tyler-smith/iexplorer/internal/db/models"
)

func TranasactionTypeBadge(t models.TxType) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		switch t {
		case models.TxTypeStandard:
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<span class=\"inline-flex h-6 shrink-0 items-center whitespace-nowrap rounded-full border border-purple-300 bg-purple-100 px-2 text-sm font-medium text-purple-600\"><i class=\"fa-solid fa-money-bill-transfer pr-1\"></i> Standard</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case models.TxTypeCoinbase:
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<span class=\"inline-flex h-6 shrink-0 items-center whitespace-nowrap rounded-full border border-purple-300 bg-purple-100 px-2 text-sm font-medium text-purple-600\"><i class=\"fa-solid fa-coins pr-1\"></i> Coinbase</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case models.TxTypeStake:
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<span class=\"inline-flex h-6 shrink-0 items-center whitespace-nowrap rounded-full border border-purple-300 bg-purple-100 px-2 text-sm font-medium text-purple-600\"><i class=\"fa-solid fa-lock pr-1\"></i> Stake</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case models.TxTypeMint:
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<span class=\"inline-flex h-6 shrink-0 items-center whitespace-nowrap rounded-full border border-purple-300 bg-purple-100 px-2 text-sm font-medium text-purple-600\"><i class=\"fa-solid fa-stamp pr-1\"></i> Mint</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case models.TxTypeTreasury:
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<span class=\"inline-flex h-6 shrink-0 items-center whitespace-nowrap rounded-full border border-purple-300 bg-purple-100 px-2 text-sm font-medium text-purple-600\"><i class=\"fa-solid fa-gavel pr-1\"></i> Treasury Proposal</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
